version: "3"

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres0
    volumes:
      - ./data/postgres/:/var/postgresql/data
  mysql:
    image: mysql:latest
    restart: always 
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql0
      MYSQL_ROOT_PASSWORD: mysql0
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    volumes:
      - ./data/mysql/:/var/mysql/data
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf --port 6379 --requirepass redis0 --appendonly yes --appendfilename "appendonly.aof"
    volumes:
      - ./data/redis/:/var/redis/data
      - ./data/redis/redis.conf:/usr/local/etc/redis/redis.conf